[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OCTOPUS"
authors = [{name = "Henry", email = "hmunack@uow.edu.au"}]
dynamic = ["version", "description"]
